// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtm/alert/model/alert_descriptor.proto

#include "mtm/alert/model/alert_descriptor.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_google_2fprotobuf_2fduration_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2fduration_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Duration;
}  // namespace protobuf_google_2fprotobuf_2fduration_2eproto
namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2ftimestamp_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Timestamp;
}  // namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto
namespace protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto ::google::protobuf::internal::SCCInfo<5> scc_info_AlertDescriptor;
}  // namespace protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto
namespace protobuf_mtm_2fcommon_5ftypes_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_mtm_2fcommon_5ftypes_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Uuid;
}  // namespace protobuf_mtm_2fcommon_5ftypes_2eproto
namespace protobuf_mtm_2fevent_2fargument_5fdescriptor_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_mtm_2fevent_2fargument_5fdescriptor_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_ArgumentDescriptor;
}  // namespace protobuf_mtm_2fevent_2fargument_5fdescriptor_2eproto
namespace mtm {
namespace alert {
namespace model {
class AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse>
      _instance;
} _AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse_default_instance_;
class AlertDescriptorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AlertDescriptor>
      _instance;
} _AlertDescriptor_default_instance_;
class AlertDescriptorListDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AlertDescriptorList>
      _instance;
} _AlertDescriptorList_default_instance_;
}  // namespace model
}  // namespace alert
}  // namespace mtm
namespace protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto {
static void InitDefaultsAlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mtm::alert::model::_AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse_default_instance_;
    new (ptr) ::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse();
  }
  ::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse}, {}};

static void InitDefaultsAlertDescriptor() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mtm::alert::model::_AlertDescriptor_default_instance_;
    new (ptr) ::mtm::alert::model::AlertDescriptor();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mtm::alert::model::AlertDescriptor::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<5> scc_info_AlertDescriptor =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 5, InitDefaultsAlertDescriptor}, {
      &protobuf_mtm_2fcommon_5ftypes_2eproto::scc_info_Uuid.base,
      &protobuf_google_2fprotobuf_2fduration_2eproto::scc_info_Duration.base,
      &protobuf_mtm_2fevent_2fargument_5fdescriptor_2eproto::scc_info_ArgumentDescriptor.base,
      &protobuf_google_2fprotobuf_2ftimestamp_2eproto::scc_info_Timestamp.base,
      &protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::scc_info_AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse.base,}};

static void InitDefaultsAlertDescriptorList() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mtm::alert::model::_AlertDescriptorList_default_instance_;
    new (ptr) ::mtm::alert::model::AlertDescriptorList();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mtm::alert::model::AlertDescriptorList::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_AlertDescriptorList =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsAlertDescriptorList}, {
      &protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::scc_info_AlertDescriptor.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_AlertDescriptor.base);
  ::google::protobuf::internal::InitSCC(&scc_info_AlertDescriptorList.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, type_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, display_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, format_string_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, auto_remove_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, auto_remove_timespan_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, removed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, arguments_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, message_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, alert_server_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, roles_acknowledge_limit_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, auto_created_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, read_access_groups_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, write_access_groups_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, execute_access_groups_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptor, category_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptorList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mtm::alert::model::AlertDescriptorList, alert_descriptors_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse)},
  { 9, -1, sizeof(::mtm::alert::model::AlertDescriptor)},
  { 30, -1, sizeof(::mtm::alert::model::AlertDescriptorList)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::mtm::alert::model::_AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mtm::alert::model::_AlertDescriptor_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mtm::alert::model::_AlertDescriptorList_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "mtm/alert/model/alert_descriptor.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n&mtm/alert/model/alert_descriptor.proto"
      "\022\017mtm.alert.model\032\037google/protobuf/times"
      "tamp.proto\032\036google/protobuf/duration.pro"
      "to\032\026mtm/common_types.proto\032#mtm/event/ar"
      "gument_descriptor.proto\"\356\004\n\017AlertDescrip"
      "tor\022\032\n\007type_id\030\001 \001(\0132\t.mtm.Uuid\022\024\n\014displ"
      "ay_name\030\002 \001(\t\022\025\n\rformat_string\030\003 \001(\t\022\023\n\013"
      "auto_remove\030\004 \001(\010\0227\n\024auto_remove_timeSpa"
      "n\030\005 \001(\0132\031.google.protobuf.Duration\022\017\n\007ve"
      "rsion\030\006 \001(\r\022\017\n\007removed\030\007 \001(\010\0220\n\targument"
      "s\030\010 \003(\0132\035.mtm.event.ArgumentDescriptor\0220"
      "\n\014message_time\030\t \001(\0132\032.google.protobuf.T"
      "imestamp\022\027\n\017alert_server_id\030\n \001(\r\022\\\n\027rol"
      "es_acknowledge_limit\030\013 \003(\0132;.mtm.alert.m"
      "odel.AlertDescriptor.RolesAcknowledgeLim"
      "itEntry\022\024\n\014auto_created\030\014 \001(\010\022\032\n\022read_ac"
      "cess_groups\030\r \003(\r\022\033\n\023write_access_groups"
      "\030\016 \003(\r\022\035\n\025execute_access_groups\030\017 \003(\r\022\033\n"
      "\010category\030\020 \001(\0132\t.mtm.Uuid\032<\n\032RolesAckno"
      "wledgeLimitEntry\022\013\n\003key\030\001 \001(\r\022\r\n\005value\030\002"
      " \001(\r:\0028\001\"R\n\023AlertDescriptorList\022;\n\021alert"
      "_descriptors\030\001 \003(\0132 .mtm.alert.model.Ale"
      "rtDescriptorb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 900);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mtm/alert/model/alert_descriptor.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2ftimestamp_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobuf_2fduration_2eproto::AddDescriptors();
  ::protobuf_mtm_2fcommon_5ftypes_2eproto::AddDescriptors();
  ::protobuf_mtm_2fevent_2fargument_5fdescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto
namespace mtm {
namespace alert {
namespace model {

// ===================================================================

AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse() {}
AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse::MergeFrom(const AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse::GetMetadata() const {
  ::protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::file_level_metadata[0];
}
void AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void AlertDescriptor::InitAsDefaultInstance() {
  ::mtm::alert::model::_AlertDescriptor_default_instance_._instance.get_mutable()->type_id_ = const_cast< ::mtm::Uuid*>(
      ::mtm::Uuid::internal_default_instance());
  ::mtm::alert::model::_AlertDescriptor_default_instance_._instance.get_mutable()->auto_remove_timespan_ = const_cast< ::google::protobuf::Duration*>(
      ::google::protobuf::Duration::internal_default_instance());
  ::mtm::alert::model::_AlertDescriptor_default_instance_._instance.get_mutable()->message_time_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
  ::mtm::alert::model::_AlertDescriptor_default_instance_._instance.get_mutable()->category_ = const_cast< ::mtm::Uuid*>(
      ::mtm::Uuid::internal_default_instance());
}
void AlertDescriptor::clear_type_id() {
  if (GetArenaNoVirtual() == NULL && type_id_ != NULL) {
    delete type_id_;
  }
  type_id_ = NULL;
}
void AlertDescriptor::clear_auto_remove_timespan() {
  if (GetArenaNoVirtual() == NULL && auto_remove_timespan_ != NULL) {
    delete auto_remove_timespan_;
  }
  auto_remove_timespan_ = NULL;
}
void AlertDescriptor::clear_arguments() {
  arguments_.Clear();
}
void AlertDescriptor::clear_message_time() {
  if (GetArenaNoVirtual() == NULL && message_time_ != NULL) {
    delete message_time_;
  }
  message_time_ = NULL;
}
void AlertDescriptor::clear_category() {
  if (GetArenaNoVirtual() == NULL && category_ != NULL) {
    delete category_;
  }
  category_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AlertDescriptor::kTypeIdFieldNumber;
const int AlertDescriptor::kDisplayNameFieldNumber;
const int AlertDescriptor::kFormatStringFieldNumber;
const int AlertDescriptor::kAutoRemoveFieldNumber;
const int AlertDescriptor::kAutoRemoveTimeSpanFieldNumber;
const int AlertDescriptor::kVersionFieldNumber;
const int AlertDescriptor::kRemovedFieldNumber;
const int AlertDescriptor::kArgumentsFieldNumber;
const int AlertDescriptor::kMessageTimeFieldNumber;
const int AlertDescriptor::kAlertServerIdFieldNumber;
const int AlertDescriptor::kRolesAcknowledgeLimitFieldNumber;
const int AlertDescriptor::kAutoCreatedFieldNumber;
const int AlertDescriptor::kReadAccessGroupsFieldNumber;
const int AlertDescriptor::kWriteAccessGroupsFieldNumber;
const int AlertDescriptor::kExecuteAccessGroupsFieldNumber;
const int AlertDescriptor::kCategoryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AlertDescriptor::AlertDescriptor()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::scc_info_AlertDescriptor.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mtm.alert.model.AlertDescriptor)
}
AlertDescriptor::AlertDescriptor(const AlertDescriptor& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      arguments_(from.arguments_),
      read_access_groups_(from.read_access_groups_),
      write_access_groups_(from.write_access_groups_),
      execute_access_groups_(from.execute_access_groups_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  roles_acknowledge_limit_.MergeFrom(from.roles_acknowledge_limit_);
  display_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.display_name().size() > 0) {
    display_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.display_name_);
  }
  format_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.format_string().size() > 0) {
    format_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.format_string_);
  }
  if (from.has_type_id()) {
    type_id_ = new ::mtm::Uuid(*from.type_id_);
  } else {
    type_id_ = NULL;
  }
  if (from.has_auto_remove_timespan()) {
    auto_remove_timespan_ = new ::google::protobuf::Duration(*from.auto_remove_timespan_);
  } else {
    auto_remove_timespan_ = NULL;
  }
  if (from.has_message_time()) {
    message_time_ = new ::google::protobuf::Timestamp(*from.message_time_);
  } else {
    message_time_ = NULL;
  }
  if (from.has_category()) {
    category_ = new ::mtm::Uuid(*from.category_);
  } else {
    category_ = NULL;
  }
  ::memcpy(&version_, &from.version_,
    static_cast<size_t>(reinterpret_cast<char*>(&alert_server_id_) -
    reinterpret_cast<char*>(&version_)) + sizeof(alert_server_id_));
  // @@protoc_insertion_point(copy_constructor:mtm.alert.model.AlertDescriptor)
}

void AlertDescriptor::SharedCtor() {
  display_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&type_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&alert_server_id_) -
      reinterpret_cast<char*>(&type_id_)) + sizeof(alert_server_id_));
}

AlertDescriptor::~AlertDescriptor() {
  // @@protoc_insertion_point(destructor:mtm.alert.model.AlertDescriptor)
  SharedDtor();
}

void AlertDescriptor::SharedDtor() {
  display_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete type_id_;
  if (this != internal_default_instance()) delete auto_remove_timespan_;
  if (this != internal_default_instance()) delete message_time_;
  if (this != internal_default_instance()) delete category_;
}

void AlertDescriptor::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AlertDescriptor::descriptor() {
  ::protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AlertDescriptor& AlertDescriptor::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::scc_info_AlertDescriptor.base);
  return *internal_default_instance();
}


void AlertDescriptor::Clear() {
// @@protoc_insertion_point(message_clear_start:mtm.alert.model.AlertDescriptor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  arguments_.Clear();
  roles_acknowledge_limit_.Clear();
  read_access_groups_.Clear();
  write_access_groups_.Clear();
  execute_access_groups_.Clear();
  display_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && type_id_ != NULL) {
    delete type_id_;
  }
  type_id_ = NULL;
  if (GetArenaNoVirtual() == NULL && auto_remove_timespan_ != NULL) {
    delete auto_remove_timespan_;
  }
  auto_remove_timespan_ = NULL;
  if (GetArenaNoVirtual() == NULL && message_time_ != NULL) {
    delete message_time_;
  }
  message_time_ = NULL;
  if (GetArenaNoVirtual() == NULL && category_ != NULL) {
    delete category_;
  }
  category_ = NULL;
  ::memset(&version_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&alert_server_id_) -
      reinterpret_cast<char*>(&version_)) + sizeof(alert_server_id_));
  _internal_metadata_.Clear();
}

bool AlertDescriptor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mtm.alert.model.AlertDescriptor)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .mtm.Uuid type_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_type_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string display_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_display_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->display_name().data(), static_cast<int>(this->display_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mtm.alert.model.AlertDescriptor.display_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string format_string = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_format_string()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->format_string().data(), static_cast<int>(this->format_string().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mtm.alert.model.AlertDescriptor.format_string"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool auto_remove = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &auto_remove_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Duration auto_remove_timeSpan = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_auto_remove_timespan()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 version = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &version_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool removed = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &removed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .mtm.event.ArgumentDescriptor arguments = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_arguments()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Timestamp message_time = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_message_time()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 alert_server_id = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &alert_server_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<uint32, uint32> roles_acknowledge_limit = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse,
              ::google::protobuf::uint32, ::google::protobuf::uint32,
              ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
              ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
              0 >,
            ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 > > parser(&roles_acknowledge_limit_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool auto_created = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &auto_created_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 read_access_groups = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_read_access_groups())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(104u /* 104 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 106u, input, this->mutable_read_access_groups())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 write_access_groups = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_write_access_groups())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(112u /* 112 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 114u, input, this->mutable_write_access_groups())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 execute_access_groups = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u /* 122 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_execute_access_groups())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(120u /* 120 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 122u, input, this->mutable_execute_access_groups())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .mtm.Uuid category = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(130u /* 130 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_category()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mtm.alert.model.AlertDescriptor)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mtm.alert.model.AlertDescriptor)
  return false;
#undef DO_
}

void AlertDescriptor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mtm.alert.model.AlertDescriptor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .mtm.Uuid type_id = 1;
  if (this->has_type_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_type_id(), output);
  }

  // string display_name = 2;
  if (this->display_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->display_name().data(), static_cast<int>(this->display_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mtm.alert.model.AlertDescriptor.display_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->display_name(), output);
  }

  // string format_string = 3;
  if (this->format_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->format_string().data(), static_cast<int>(this->format_string().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mtm.alert.model.AlertDescriptor.format_string");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->format_string(), output);
  }

  // bool auto_remove = 4;
  if (this->auto_remove() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->auto_remove(), output);
  }

  // .google.protobuf.Duration auto_remove_timeSpan = 5;
  if (this->has_auto_remove_timespan()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_auto_remove_timespan(), output);
  }

  // uint32 version = 6;
  if (this->version() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->version(), output);
  }

  // bool removed = 7;
  if (this->removed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->removed(), output);
  }

  // repeated .mtm.event.ArgumentDescriptor arguments = 8;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->arguments_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8,
      this->arguments(static_cast<int>(i)),
      output);
  }

  // .google.protobuf.Timestamp message_time = 9;
  if (this->has_message_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, this->_internal_message_time(), output);
  }

  // uint32 alert_server_id = 10;
  if (this->alert_server_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->alert_server_id(), output);
  }

  // map<uint32, uint32> roles_acknowledge_limit = 11;
  if (!this->roles_acknowledge_limit().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::uint32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (output->IsSerializationDeterministic() &&
        this->roles_acknowledge_limit().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->roles_acknowledge_limit().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >::const_iterator
          it = this->roles_acknowledge_limit().begin();
          it != this->roles_acknowledge_limit().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(roles_acknowledge_limit_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            11, *entry, output);
      }
    } else {
      ::std::unique_ptr<AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >::const_iterator
          it = this->roles_acknowledge_limit().begin();
          it != this->roles_acknowledge_limit().end(); ++it) {
        entry.reset(roles_acknowledge_limit_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            11, *entry, output);
      }
    }
  }

  // bool auto_created = 12;
  if (this->auto_created() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->auto_created(), output);
  }

  // repeated uint32 read_access_groups = 13;
  if (this->read_access_groups_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(13, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _read_access_groups_cached_byte_size_));
  }
  for (int i = 0, n = this->read_access_groups_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->read_access_groups(i), output);
  }

  // repeated uint32 write_access_groups = 14;
  if (this->write_access_groups_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(14, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _write_access_groups_cached_byte_size_));
  }
  for (int i = 0, n = this->write_access_groups_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->write_access_groups(i), output);
  }

  // repeated uint32 execute_access_groups = 15;
  if (this->execute_access_groups_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(15, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _execute_access_groups_cached_byte_size_));
  }
  for (int i = 0, n = this->execute_access_groups_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->execute_access_groups(i), output);
  }

  // .mtm.Uuid category = 16;
  if (this->has_category()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      16, this->_internal_category(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mtm.alert.model.AlertDescriptor)
}

::google::protobuf::uint8* AlertDescriptor::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mtm.alert.model.AlertDescriptor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .mtm.Uuid type_id = 1;
  if (this->has_type_id()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_type_id(), deterministic, target);
  }

  // string display_name = 2;
  if (this->display_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->display_name().data(), static_cast<int>(this->display_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mtm.alert.model.AlertDescriptor.display_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->display_name(), target);
  }

  // string format_string = 3;
  if (this->format_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->format_string().data(), static_cast<int>(this->format_string().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mtm.alert.model.AlertDescriptor.format_string");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->format_string(), target);
  }

  // bool auto_remove = 4;
  if (this->auto_remove() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->auto_remove(), target);
  }

  // .google.protobuf.Duration auto_remove_timeSpan = 5;
  if (this->has_auto_remove_timespan()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_auto_remove_timespan(), deterministic, target);
  }

  // uint32 version = 6;
  if (this->version() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->version(), target);
  }

  // bool removed = 7;
  if (this->removed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->removed(), target);
  }

  // repeated .mtm.event.ArgumentDescriptor arguments = 8;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->arguments_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        8, this->arguments(static_cast<int>(i)), deterministic, target);
  }

  // .google.protobuf.Timestamp message_time = 9;
  if (this->has_message_time()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        9, this->_internal_message_time(), deterministic, target);
  }

  // uint32 alert_server_id = 10;
  if (this->alert_server_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->alert_server_id(), target);
  }

  // map<uint32, uint32> roles_acknowledge_limit = 11;
  if (!this->roles_acknowledge_limit().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::uint32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (deterministic &&
        this->roles_acknowledge_limit().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->roles_acknowledge_limit().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >::const_iterator
          it = this->roles_acknowledge_limit().begin();
          it != this->roles_acknowledge_limit().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(roles_acknowledge_limit_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       11, *entry, deterministic, target);
;
      }
    } else {
      ::std::unique_ptr<AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >::const_iterator
          it = this->roles_acknowledge_limit().begin();
          it != this->roles_acknowledge_limit().end(); ++it) {
        entry.reset(roles_acknowledge_limit_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       11, *entry, deterministic, target);
;
      }
    }
  }

  // bool auto_created = 12;
  if (this->auto_created() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->auto_created(), target);
  }

  // repeated uint32 read_access_groups = 13;
  if (this->read_access_groups_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      13,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _read_access_groups_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->read_access_groups_, target);
  }

  // repeated uint32 write_access_groups = 14;
  if (this->write_access_groups_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      14,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _write_access_groups_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->write_access_groups_, target);
  }

  // repeated uint32 execute_access_groups = 15;
  if (this->execute_access_groups_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      15,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _execute_access_groups_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->execute_access_groups_, target);
  }

  // .mtm.Uuid category = 16;
  if (this->has_category()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        16, this->_internal_category(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mtm.alert.model.AlertDescriptor)
  return target;
}

size_t AlertDescriptor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mtm.alert.model.AlertDescriptor)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .mtm.event.ArgumentDescriptor arguments = 8;
  {
    unsigned int count = static_cast<unsigned int>(this->arguments_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->arguments(static_cast<int>(i)));
    }
  }

  // map<uint32, uint32> roles_acknowledge_limit = 11;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->roles_acknowledge_limit_size());
  {
    ::std::unique_ptr<AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >::const_iterator
        it = this->roles_acknowledge_limit().begin();
        it != this->roles_acknowledge_limit().end(); ++it) {
      entry.reset(roles_acknowledge_limit_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // repeated uint32 read_access_groups = 13;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->read_access_groups_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _read_access_groups_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated uint32 write_access_groups = 14;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->write_access_groups_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _write_access_groups_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated uint32 execute_access_groups = 15;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->execute_access_groups_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _execute_access_groups_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string display_name = 2;
  if (this->display_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->display_name());
  }

  // string format_string = 3;
  if (this->format_string().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->format_string());
  }

  // .mtm.Uuid type_id = 1;
  if (this->has_type_id()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *type_id_);
  }

  // .google.protobuf.Duration auto_remove_timeSpan = 5;
  if (this->has_auto_remove_timespan()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *auto_remove_timespan_);
  }

  // .google.protobuf.Timestamp message_time = 9;
  if (this->has_message_time()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *message_time_);
  }

  // .mtm.Uuid category = 16;
  if (this->has_category()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *category_);
  }

  // uint32 version = 6;
  if (this->version() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->version());
  }

  // bool auto_remove = 4;
  if (this->auto_remove() != 0) {
    total_size += 1 + 1;
  }

  // bool removed = 7;
  if (this->removed() != 0) {
    total_size += 1 + 1;
  }

  // bool auto_created = 12;
  if (this->auto_created() != 0) {
    total_size += 1 + 1;
  }

  // uint32 alert_server_id = 10;
  if (this->alert_server_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->alert_server_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AlertDescriptor::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mtm.alert.model.AlertDescriptor)
  GOOGLE_DCHECK_NE(&from, this);
  const AlertDescriptor* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AlertDescriptor>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mtm.alert.model.AlertDescriptor)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mtm.alert.model.AlertDescriptor)
    MergeFrom(*source);
  }
}

void AlertDescriptor::MergeFrom(const AlertDescriptor& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mtm.alert.model.AlertDescriptor)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  arguments_.MergeFrom(from.arguments_);
  roles_acknowledge_limit_.MergeFrom(from.roles_acknowledge_limit_);
  read_access_groups_.MergeFrom(from.read_access_groups_);
  write_access_groups_.MergeFrom(from.write_access_groups_);
  execute_access_groups_.MergeFrom(from.execute_access_groups_);
  if (from.display_name().size() > 0) {

    display_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.display_name_);
  }
  if (from.format_string().size() > 0) {

    format_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.format_string_);
  }
  if (from.has_type_id()) {
    mutable_type_id()->::mtm::Uuid::MergeFrom(from.type_id());
  }
  if (from.has_auto_remove_timespan()) {
    mutable_auto_remove_timespan()->::google::protobuf::Duration::MergeFrom(from.auto_remove_timespan());
  }
  if (from.has_message_time()) {
    mutable_message_time()->::google::protobuf::Timestamp::MergeFrom(from.message_time());
  }
  if (from.has_category()) {
    mutable_category()->::mtm::Uuid::MergeFrom(from.category());
  }
  if (from.version() != 0) {
    set_version(from.version());
  }
  if (from.auto_remove() != 0) {
    set_auto_remove(from.auto_remove());
  }
  if (from.removed() != 0) {
    set_removed(from.removed());
  }
  if (from.auto_created() != 0) {
    set_auto_created(from.auto_created());
  }
  if (from.alert_server_id() != 0) {
    set_alert_server_id(from.alert_server_id());
  }
}

void AlertDescriptor::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mtm.alert.model.AlertDescriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AlertDescriptor::CopyFrom(const AlertDescriptor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mtm.alert.model.AlertDescriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AlertDescriptor::IsInitialized() const {
  return true;
}

void AlertDescriptor::Swap(AlertDescriptor* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AlertDescriptor::InternalSwap(AlertDescriptor* other) {
  using std::swap;
  CastToBase(&arguments_)->InternalSwap(CastToBase(&other->arguments_));
  roles_acknowledge_limit_.Swap(&other->roles_acknowledge_limit_);
  read_access_groups_.InternalSwap(&other->read_access_groups_);
  write_access_groups_.InternalSwap(&other->write_access_groups_);
  execute_access_groups_.InternalSwap(&other->execute_access_groups_);
  display_name_.Swap(&other->display_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  format_string_.Swap(&other->format_string_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(type_id_, other->type_id_);
  swap(auto_remove_timespan_, other->auto_remove_timespan_);
  swap(message_time_, other->message_time_);
  swap(category_, other->category_);
  swap(version_, other->version_);
  swap(auto_remove_, other->auto_remove_);
  swap(removed_, other->removed_);
  swap(auto_created_, other->auto_created_);
  swap(alert_server_id_, other->alert_server_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AlertDescriptor::GetMetadata() const {
  protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void AlertDescriptorList::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AlertDescriptorList::kAlertDescriptorsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AlertDescriptorList::AlertDescriptorList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::scc_info_AlertDescriptorList.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mtm.alert.model.AlertDescriptorList)
}
AlertDescriptorList::AlertDescriptorList(const AlertDescriptorList& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      alert_descriptors_(from.alert_descriptors_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mtm.alert.model.AlertDescriptorList)
}

void AlertDescriptorList::SharedCtor() {
}

AlertDescriptorList::~AlertDescriptorList() {
  // @@protoc_insertion_point(destructor:mtm.alert.model.AlertDescriptorList)
  SharedDtor();
}

void AlertDescriptorList::SharedDtor() {
}

void AlertDescriptorList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AlertDescriptorList::descriptor() {
  ::protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AlertDescriptorList& AlertDescriptorList::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::scc_info_AlertDescriptorList.base);
  return *internal_default_instance();
}


void AlertDescriptorList::Clear() {
// @@protoc_insertion_point(message_clear_start:mtm.alert.model.AlertDescriptorList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  alert_descriptors_.Clear();
  _internal_metadata_.Clear();
}

bool AlertDescriptorList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mtm.alert.model.AlertDescriptorList)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .mtm.alert.model.AlertDescriptor alert_descriptors = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_alert_descriptors()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mtm.alert.model.AlertDescriptorList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mtm.alert.model.AlertDescriptorList)
  return false;
#undef DO_
}

void AlertDescriptorList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mtm.alert.model.AlertDescriptorList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .mtm.alert.model.AlertDescriptor alert_descriptors = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->alert_descriptors_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->alert_descriptors(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mtm.alert.model.AlertDescriptorList)
}

::google::protobuf::uint8* AlertDescriptorList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mtm.alert.model.AlertDescriptorList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .mtm.alert.model.AlertDescriptor alert_descriptors = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->alert_descriptors_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->alert_descriptors(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mtm.alert.model.AlertDescriptorList)
  return target;
}

size_t AlertDescriptorList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mtm.alert.model.AlertDescriptorList)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .mtm.alert.model.AlertDescriptor alert_descriptors = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->alert_descriptors_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->alert_descriptors(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AlertDescriptorList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mtm.alert.model.AlertDescriptorList)
  GOOGLE_DCHECK_NE(&from, this);
  const AlertDescriptorList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AlertDescriptorList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mtm.alert.model.AlertDescriptorList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mtm.alert.model.AlertDescriptorList)
    MergeFrom(*source);
  }
}

void AlertDescriptorList::MergeFrom(const AlertDescriptorList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mtm.alert.model.AlertDescriptorList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  alert_descriptors_.MergeFrom(from.alert_descriptors_);
}

void AlertDescriptorList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mtm.alert.model.AlertDescriptorList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AlertDescriptorList::CopyFrom(const AlertDescriptorList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mtm.alert.model.AlertDescriptorList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AlertDescriptorList::IsInitialized() const {
  return true;
}

void AlertDescriptorList::Swap(AlertDescriptorList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AlertDescriptorList::InternalSwap(AlertDescriptorList* other) {
  using std::swap;
  CastToBase(&alert_descriptors_)->InternalSwap(CastToBase(&other->alert_descriptors_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AlertDescriptorList::GetMetadata() const {
  protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mtm_2falert_2fmodel_2falert_5fdescriptor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace model
}  // namespace alert
}  // namespace mtm
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse* Arena::CreateMaybeMessage< ::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::mtm::alert::model::AlertDescriptor_RolesAcknowledgeLimitEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mtm::alert::model::AlertDescriptor* Arena::CreateMaybeMessage< ::mtm::alert::model::AlertDescriptor >(Arena* arena) {
  return Arena::CreateInternal< ::mtm::alert::model::AlertDescriptor >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mtm::alert::model::AlertDescriptorList* Arena::CreateMaybeMessage< ::mtm::alert::model::AlertDescriptorList >(Arena* arena) {
  return Arena::CreateInternal< ::mtm::alert::model::AlertDescriptorList >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
