// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtm/event/event.proto

#ifndef PROTOBUF_INCLUDED_mtm_2fevent_2fevent_2eproto
#define PROTOBUF_INCLUDED_mtm_2fevent_2fevent_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include "mtm/common_types.pb.h"
#include "mtm/event/argument.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_mtm_2fevent_2fevent_2eproto 

namespace protobuf_mtm_2fevent_2fevent_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_mtm_2fevent_2fevent_2eproto
namespace mtm {
namespace event {
class Event;
class EventDefaultTypeInternal;
extern EventDefaultTypeInternal _Event_default_instance_;
}  // namespace event
}  // namespace mtm
namespace google {
namespace protobuf {
template<> ::mtm::event::Event* Arena::CreateMaybeMessage<::mtm::event::Event>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace mtm {
namespace event {

// ===================================================================

class Event : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mtm.event.Event) */ {
 public:
  Event();
  virtual ~Event();

  Event(const Event& from);

  inline Event& operator=(const Event& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Event(Event&& from) noexcept
    : Event() {
    *this = ::std::move(from);
  }

  inline Event& operator=(Event&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Event& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Event* internal_default_instance() {
    return reinterpret_cast<const Event*>(
               &_Event_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Event* other);
  friend void swap(Event& a, Event& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Event* New() const final {
    return CreateMaybeMessage<Event>(NULL);
  }

  Event* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Event>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Event& from);
  void MergeFrom(const Event& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Event* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .mtm.event.Argument arguments = 10;
  int arguments_size() const;
  void clear_arguments();
  static const int kArgumentsFieldNumber = 10;
  ::mtm::event::Argument* mutable_arguments(int index);
  ::google::protobuf::RepeatedPtrField< ::mtm::event::Argument >*
      mutable_arguments();
  const ::mtm::event::Argument& arguments(int index) const;
  ::mtm::event::Argument* add_arguments();
  const ::google::protobuf::RepeatedPtrField< ::mtm::event::Argument >&
      arguments() const;

  // .google.protobuf.Timestamp time = 1;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  private:
  const ::google::protobuf::Timestamp& _internal_time() const;
  public:
  const ::google::protobuf::Timestamp& time() const;
  ::google::protobuf::Timestamp* release_time();
  ::google::protobuf::Timestamp* mutable_time();
  void set_allocated_time(::google::protobuf::Timestamp* time);

  // .mtm.Uuid id = 2;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 2;
  private:
  const ::mtm::Uuid& _internal_id() const;
  public:
  const ::mtm::Uuid& id() const;
  ::mtm::Uuid* release_id();
  ::mtm::Uuid* mutable_id();
  void set_allocated_id(::mtm::Uuid* id);

  // .mtm.Uuid event_type_id = 3;
  bool has_event_type_id() const;
  void clear_event_type_id();
  static const int kEventTypeIdFieldNumber = 3;
  private:
  const ::mtm::Uuid& _internal_event_type_id() const;
  public:
  const ::mtm::Uuid& event_type_id() const;
  ::mtm::Uuid* release_event_type_id();
  ::mtm::Uuid* mutable_event_type_id();
  void set_allocated_event_type_id(::mtm::Uuid* event_type_id);

  // .mtm.Uuid source_type = 5;
  bool has_source_type() const;
  void clear_source_type();
  static const int kSourceTypeFieldNumber = 5;
  private:
  const ::mtm::Uuid& _internal_source_type() const;
  public:
  const ::mtm::Uuid& source_type() const;
  ::mtm::Uuid* release_source_type();
  ::mtm::Uuid* mutable_source_type();
  void set_allocated_source_type(::mtm::Uuid* source_type);

  // .mtm.Uuid sent_by_type = 7;
  bool has_sent_by_type() const;
  void clear_sent_by_type();
  static const int kSentByTypeFieldNumber = 7;
  private:
  const ::mtm::Uuid& _internal_sent_by_type() const;
  public:
  const ::mtm::Uuid& sent_by_type() const;
  ::mtm::Uuid* release_sent_by_type();
  ::mtm::Uuid* mutable_sent_by_type();
  void set_allocated_sent_by_type(::mtm::Uuid* sent_by_type);

  // uint32 source_system_id = 4;
  void clear_source_system_id();
  static const int kSourceSystemIdFieldNumber = 4;
  ::google::protobuf::uint32 source_system_id() const;
  void set_source_system_id(::google::protobuf::uint32 value);

  // uint32 sent_by_system_id = 6;
  void clear_sent_by_system_id();
  static const int kSentBySystemIdFieldNumber = 6;
  ::google::protobuf::uint32 sent_by_system_id() const;
  void set_sent_by_system_id(::google::protobuf::uint32 value);

  // uint32 operator_account_system_id = 8;
  void clear_operator_account_system_id();
  static const int kOperatorAccountSystemIdFieldNumber = 8;
  ::google::protobuf::uint32 operator_account_system_id() const;
  void set_operator_account_system_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mtm.event.Event)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::mtm::event::Argument > arguments_;
  ::google::protobuf::Timestamp* time_;
  ::mtm::Uuid* id_;
  ::mtm::Uuid* event_type_id_;
  ::mtm::Uuid* source_type_;
  ::mtm::Uuid* sent_by_type_;
  ::google::protobuf::uint32 source_system_id_;
  ::google::protobuf::uint32 sent_by_system_id_;
  ::google::protobuf::uint32 operator_account_system_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mtm_2fevent_2fevent_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Event

// .google.protobuf.Timestamp time = 1;
inline bool Event::has_time() const {
  return this != internal_default_instance() && time_ != NULL;
}
inline const ::google::protobuf::Timestamp& Event::_internal_time() const {
  return *time_;
}
inline const ::google::protobuf::Timestamp& Event::time() const {
  const ::google::protobuf::Timestamp* p = time_;
  // @@protoc_insertion_point(field_get:mtm.event.Event.time)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Timestamp*>(
      &::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* Event::release_time() {
  // @@protoc_insertion_point(field_release:mtm.event.Event.time)
  
  ::google::protobuf::Timestamp* temp = time_;
  time_ = NULL;
  return temp;
}
inline ::google::protobuf::Timestamp* Event::mutable_time() {
  
  if (time_ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::Timestamp>(GetArenaNoVirtual());
    time_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mtm.event.Event.time)
  return time_;
}
inline void Event::set_allocated_time(::google::protobuf::Timestamp* time) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(time_);
  }
  if (time) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(time)->GetArena();
    if (message_arena != submessage_arena) {
      time = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, time, submessage_arena);
    }
    
  } else {
    
  }
  time_ = time;
  // @@protoc_insertion_point(field_set_allocated:mtm.event.Event.time)
}

// .mtm.Uuid id = 2;
inline bool Event::has_id() const {
  return this != internal_default_instance() && id_ != NULL;
}
inline const ::mtm::Uuid& Event::_internal_id() const {
  return *id_;
}
inline const ::mtm::Uuid& Event::id() const {
  const ::mtm::Uuid* p = id_;
  // @@protoc_insertion_point(field_get:mtm.event.Event.id)
  return p != NULL ? *p : *reinterpret_cast<const ::mtm::Uuid*>(
      &::mtm::_Uuid_default_instance_);
}
inline ::mtm::Uuid* Event::release_id() {
  // @@protoc_insertion_point(field_release:mtm.event.Event.id)
  
  ::mtm::Uuid* temp = id_;
  id_ = NULL;
  return temp;
}
inline ::mtm::Uuid* Event::mutable_id() {
  
  if (id_ == NULL) {
    auto* p = CreateMaybeMessage<::mtm::Uuid>(GetArenaNoVirtual());
    id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mtm.event.Event.id)
  return id_;
}
inline void Event::set_allocated_id(::mtm::Uuid* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(id_);
  }
  if (id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    
  } else {
    
  }
  id_ = id;
  // @@protoc_insertion_point(field_set_allocated:mtm.event.Event.id)
}

// .mtm.Uuid event_type_id = 3;
inline bool Event::has_event_type_id() const {
  return this != internal_default_instance() && event_type_id_ != NULL;
}
inline const ::mtm::Uuid& Event::_internal_event_type_id() const {
  return *event_type_id_;
}
inline const ::mtm::Uuid& Event::event_type_id() const {
  const ::mtm::Uuid* p = event_type_id_;
  // @@protoc_insertion_point(field_get:mtm.event.Event.event_type_id)
  return p != NULL ? *p : *reinterpret_cast<const ::mtm::Uuid*>(
      &::mtm::_Uuid_default_instance_);
}
inline ::mtm::Uuid* Event::release_event_type_id() {
  // @@protoc_insertion_point(field_release:mtm.event.Event.event_type_id)
  
  ::mtm::Uuid* temp = event_type_id_;
  event_type_id_ = NULL;
  return temp;
}
inline ::mtm::Uuid* Event::mutable_event_type_id() {
  
  if (event_type_id_ == NULL) {
    auto* p = CreateMaybeMessage<::mtm::Uuid>(GetArenaNoVirtual());
    event_type_id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mtm.event.Event.event_type_id)
  return event_type_id_;
}
inline void Event::set_allocated_event_type_id(::mtm::Uuid* event_type_id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(event_type_id_);
  }
  if (event_type_id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      event_type_id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, event_type_id, submessage_arena);
    }
    
  } else {
    
  }
  event_type_id_ = event_type_id;
  // @@protoc_insertion_point(field_set_allocated:mtm.event.Event.event_type_id)
}

// uint32 source_system_id = 4;
inline void Event::clear_source_system_id() {
  source_system_id_ = 0u;
}
inline ::google::protobuf::uint32 Event::source_system_id() const {
  // @@protoc_insertion_point(field_get:mtm.event.Event.source_system_id)
  return source_system_id_;
}
inline void Event::set_source_system_id(::google::protobuf::uint32 value) {
  
  source_system_id_ = value;
  // @@protoc_insertion_point(field_set:mtm.event.Event.source_system_id)
}

// .mtm.Uuid source_type = 5;
inline bool Event::has_source_type() const {
  return this != internal_default_instance() && source_type_ != NULL;
}
inline const ::mtm::Uuid& Event::_internal_source_type() const {
  return *source_type_;
}
inline const ::mtm::Uuid& Event::source_type() const {
  const ::mtm::Uuid* p = source_type_;
  // @@protoc_insertion_point(field_get:mtm.event.Event.source_type)
  return p != NULL ? *p : *reinterpret_cast<const ::mtm::Uuid*>(
      &::mtm::_Uuid_default_instance_);
}
inline ::mtm::Uuid* Event::release_source_type() {
  // @@protoc_insertion_point(field_release:mtm.event.Event.source_type)
  
  ::mtm::Uuid* temp = source_type_;
  source_type_ = NULL;
  return temp;
}
inline ::mtm::Uuid* Event::mutable_source_type() {
  
  if (source_type_ == NULL) {
    auto* p = CreateMaybeMessage<::mtm::Uuid>(GetArenaNoVirtual());
    source_type_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mtm.event.Event.source_type)
  return source_type_;
}
inline void Event::set_allocated_source_type(::mtm::Uuid* source_type) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(source_type_);
  }
  if (source_type) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      source_type = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, source_type, submessage_arena);
    }
    
  } else {
    
  }
  source_type_ = source_type;
  // @@protoc_insertion_point(field_set_allocated:mtm.event.Event.source_type)
}

// uint32 sent_by_system_id = 6;
inline void Event::clear_sent_by_system_id() {
  sent_by_system_id_ = 0u;
}
inline ::google::protobuf::uint32 Event::sent_by_system_id() const {
  // @@protoc_insertion_point(field_get:mtm.event.Event.sent_by_system_id)
  return sent_by_system_id_;
}
inline void Event::set_sent_by_system_id(::google::protobuf::uint32 value) {
  
  sent_by_system_id_ = value;
  // @@protoc_insertion_point(field_set:mtm.event.Event.sent_by_system_id)
}

// .mtm.Uuid sent_by_type = 7;
inline bool Event::has_sent_by_type() const {
  return this != internal_default_instance() && sent_by_type_ != NULL;
}
inline const ::mtm::Uuid& Event::_internal_sent_by_type() const {
  return *sent_by_type_;
}
inline const ::mtm::Uuid& Event::sent_by_type() const {
  const ::mtm::Uuid* p = sent_by_type_;
  // @@protoc_insertion_point(field_get:mtm.event.Event.sent_by_type)
  return p != NULL ? *p : *reinterpret_cast<const ::mtm::Uuid*>(
      &::mtm::_Uuid_default_instance_);
}
inline ::mtm::Uuid* Event::release_sent_by_type() {
  // @@protoc_insertion_point(field_release:mtm.event.Event.sent_by_type)
  
  ::mtm::Uuid* temp = sent_by_type_;
  sent_by_type_ = NULL;
  return temp;
}
inline ::mtm::Uuid* Event::mutable_sent_by_type() {
  
  if (sent_by_type_ == NULL) {
    auto* p = CreateMaybeMessage<::mtm::Uuid>(GetArenaNoVirtual());
    sent_by_type_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mtm.event.Event.sent_by_type)
  return sent_by_type_;
}
inline void Event::set_allocated_sent_by_type(::mtm::Uuid* sent_by_type) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(sent_by_type_);
  }
  if (sent_by_type) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      sent_by_type = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, sent_by_type, submessage_arena);
    }
    
  } else {
    
  }
  sent_by_type_ = sent_by_type;
  // @@protoc_insertion_point(field_set_allocated:mtm.event.Event.sent_by_type)
}

// uint32 operator_account_system_id = 8;
inline void Event::clear_operator_account_system_id() {
  operator_account_system_id_ = 0u;
}
inline ::google::protobuf::uint32 Event::operator_account_system_id() const {
  // @@protoc_insertion_point(field_get:mtm.event.Event.operator_account_system_id)
  return operator_account_system_id_;
}
inline void Event::set_operator_account_system_id(::google::protobuf::uint32 value) {
  
  operator_account_system_id_ = value;
  // @@protoc_insertion_point(field_set:mtm.event.Event.operator_account_system_id)
}

// repeated .mtm.event.Argument arguments = 10;
inline int Event::arguments_size() const {
  return arguments_.size();
}
inline ::mtm::event::Argument* Event::mutable_arguments(int index) {
  // @@protoc_insertion_point(field_mutable:mtm.event.Event.arguments)
  return arguments_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::mtm::event::Argument >*
Event::mutable_arguments() {
  // @@protoc_insertion_point(field_mutable_list:mtm.event.Event.arguments)
  return &arguments_;
}
inline const ::mtm::event::Argument& Event::arguments(int index) const {
  // @@protoc_insertion_point(field_get:mtm.event.Event.arguments)
  return arguments_.Get(index);
}
inline ::mtm::event::Argument* Event::add_arguments() {
  // @@protoc_insertion_point(field_add:mtm.event.Event.arguments)
  return arguments_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mtm::event::Argument >&
Event::arguments() const {
  // @@protoc_insertion_point(field_list:mtm.event.Event.arguments)
  return arguments_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace event
}  // namespace mtm

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_mtm_2fevent_2fevent_2eproto
